---
# This playbook contains common plays that will be run on all nodes.



- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Create variable from command
  command: "echo Hello"
  register: command_output
- debug: msg="{{command_output.stdout}}"
