---
# This playbook contains common plays that will be run on all nodes.



- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: true
- debug: msg="{{sestatus.stdout}}"

- name: Create variable from ehhco
  command: "echo Hello"
  register: command_output
- debug: msg="{{command_output.stdout}}"


- name: Create variable from  /etc/hosts
  command: cat /etc/hosts
  register: command_output1
- debug: msg="{{command_output1.stdout}}"


   
