---
# This playbook contains common plays that will be run on all nodes.

- name: test setface
  set_fact:
    interfaces_list: "{{ ansible_interfaces | select('match', '^(eth|wlan)[0-9]+') | list}}"
- debug:
    msg: The interface's list on "{{ ansible_hostname }}" is "{{ interfaces_list }}"

- debug: msg="The operating system is {{ ansible_distribution }}" 
 
- name: Execute the command only rhel77 server
  become: yes
  become_user: root 
  shell: "hostname"
  register: mynode
  when: ansible_hostname == 'rhel77'
- debug: var=mynode 


- debug:
    msg: "{{ansible_hostname}}"

# Print the Dictionary
- debug:
    msg: "{{ansible_mounts}}"

# Parsing through Variable Dictionary
- debug:
    msg: "Mount Point {{item.mount}} is at {{item.block_used/item.block_total*100}} percent "
  loop: "{{ansible_mounts}}"


#- debug: msg="The operating system is {{ ansible_distribution }}" 


- name: Add jorgetest group
  group:
    name: jorgetest
    gid: 598240
    state: present

- name: Download and untar perl mod
  unarchive:
    src: https://dlcdn.apache.org/perl/mod_perl-2.0.12.tar.gz
    dest: /home/jorge
    remote_src: yes
    creates: /home/jorge/mod_perl-2.0.12
    validate_certs: no
    owner: jorge
    group: jorge
    
- name: update permissions
  file:
    path: /home/jorge/mod_perl-2.0.12
    recurse: yes
    mode: '0755'
  

- name: Disable auto logout part 1
  replace:
    path: /etc/ssh/sshd_config
    regexp: 'ClientAliveInterval'
    replace: '#ClientAliveInterval'
  

- name: Add jorgetest group
  command: "getent passwd jorge"
  register: getent
- debug: msg="{{getent.stdout}}"

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: true
- debug: msg="{{sestatus.stdout}}"

- name: Create variable from ehhco
  command: "echo Hello"
  register: command_output
- debug: msg="{{command_output.stdout}}"


- name: Create variable from  /etc/hosts
  command: cat /etc/hosts
  register: command_output1
- debug: msg="{{command_output1.stdout}}"


   
